#!/usr/bin/env python3
"""
07_make_beast_xml.py — generate a BEAST2 XML from a labelled alignment.

Produces a standard tip-dated analysis:
    HKY+G4 substitution model
    uncorrelated relaxed lognormal clock, rate prior centred on --rate
    constant-population coalescent
    tip dates parsed from the labels

Also writes a traits file (taxon -> host group) for adding discrete trait analysis
in BEAUti, and can generate date-randomised replicates for the temporal signal test.

Usage
-----
    # main analysis
    python scripts/07_make_beast_xml.py \\
        --aln data/processed/H_clade_3_clean.fasta \\
        --out beast/clade3 --rate 7.46e-4 --chain 100000000

    # 20 date-randomised replicates for the DRT
    python scripts/07_make_beast_xml.py \\
        --aln data/processed/H_clade_3_clean.fasta \\
        --out beast/drt --rate 7.46e-4 --chain 20000000 --randomize-dates 20

Tip labels must be  ACCESSION|host_group|decimal_year

IMPORTANT
---------
Open the generated XML in BEAUti before running it (File > Load). BEAUti will
report any incompatibility with your BEAST version, and lets you inspect every
prior. Do not run a chain for days without that check. This script targets
BEAST 2.7.x namespaces.
"""

import argparse
import random
import sys
import xml.etree.ElementTree as ET
from pathlib import Path

# Namespaces BEAST searches when resolving an unqualified spec= name.
# beast.base.inference.operator is required for ScaleOperator / DeltaExchangeOperator;
# beast.base.evolution.operator for the tree operators. Omitting either produces
# "Class could not be found" errors at load time.
NS = ("beast.base.evolution.alignment:beast.base.evolution.tree.coalescent:"
      "beast.base.util:beast.base.evolution.nuc:"
      "beast.base.evolution.operator:beast.base.evolution.operator.kernel:"
      "beast.base.inference.operator:beast.base.inference.operator.kernel:"
      "beast.base.evolution.sitemodel:beast.base.evolution.substitutionmodel:"
      "beast.base.evolution.likelihood:beast.base.inference:"
      "beast.base.inference.parameter:beast.base.inference.distribution:"
      "beast.base.evolution.branchratemodel:beast.base.evolution.speciation")


def read_fasta(path: Path) -> dict[str, str]:
    seqs, name, chunks = {}, None, []
    for line in path.read_text().splitlines():
        if line.startswith(">"):
            if name is not None:
                seqs[name] = "".join(chunks)
            name, chunks = line[1:].split()[0], []
        elif line.strip():
            chunks.append(line.strip())
    if name is not None:
        seqs[name] = "".join(chunks)
    return seqs


def parse_labels(seqs):
    out = {}
    bad = []
    for label in seqs:
        parts = label.split("|")
        if len(parts) < 3:
            bad.append(label); continue
        try:
            year = float(parts[-1])
        except ValueError:
            bad.append(label); continue
        out[label] = (parts[0], parts[1], year)
    return out, bad


def build_xml(seqs, info, rate, chain, log_every, prefix, seed_note=""):
    """Assemble the XML as text. Kept as a template for readability."""
    seq_blocks = "\n".join(
        f'        <sequence id="seq_{lbl}" spec="Sequence" taxon="{lbl}" '
        f'totalcount="4" value="{s}"/>'
        for lbl, s in seqs.items())

    dates = ",".join(f"{lbl}={info[lbl][2]:.4f}" for lbl in seqs)
    traits = ",".join(f"{lbl}={info[lbl][1]}" for lbl in seqs)
    n = len(seqs)

    return f'''<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!-- Generated by 07_make_beast_xml.py
     {n} sequences | rate prior centred on {rate:g} subs/site/year
     HKY+G4 | uncorrelated relaxed lognormal clock | constant coalescent
     {seed_note}
     VERIFY IN BEAUti BEFORE RUNNING. -->
<beast beautitemplate="Standard" beautistatus="" namespace="{NS}" required="" version="2.7">

    <data id="{prefix}" spec="Alignment" name="alignment">
{seq_blocks}
    </data>

    <map name="Uniform">beast.base.inference.distribution.Uniform</map>
    <map name="Exponential">beast.base.inference.distribution.Exponential</map>
    <map name="LogNormal">beast.base.inference.distribution.LogNormalDistributionModel</map>
    <map name="Normal">beast.base.inference.distribution.Normal</map>
    <map name="Gamma">beast.base.inference.distribution.Gamma</map>
    <map name="OneOnX">beast.base.inference.distribution.OneOnX</map>
    <map name="prior">beast.base.inference.distribution.Prior</map>
    <map name="Beta">beast.base.inference.distribution.Beta</map>

    <run id="mcmc" spec="beast.base.inference.MCMC" chainLength="{chain}">

        <state id="state" spec="State" storeEvery="5000">
            <tree id="Tree.t:{prefix}" spec="beast.base.evolution.tree.Tree" name="stateNode">
                <trait id="dateTrait.t:{prefix}" spec="beast.base.evolution.tree.TraitSet"
                       traitname="date-forward" value="{dates}">
                    <taxa id="TaxonSet.{prefix}" spec="TaxonSet">
                        <alignment idref="{prefix}"/>
                    </taxa>
                </trait>
                <taxonset idref="TaxonSet.{prefix}"/>
            </tree>
            <parameter id="kappa.s:{prefix}" spec="parameter.RealParameter" lower="0.0" name="stateNode">2.0</parameter>
            <parameter id="gammaShape.s:{prefix}" spec="parameter.RealParameter" name="stateNode">1.0</parameter>
            <parameter id="freqParameter.s:{prefix}" spec="parameter.RealParameter" dimension="4" lower="0.0" name="stateNode" upper="1.0">0.25</parameter>
            <parameter id="popSize.t:{prefix}" spec="parameter.RealParameter" name="stateNode">0.3</parameter>
            <parameter id="ucldMean.c:{prefix}" spec="parameter.RealParameter" name="stateNode">{rate:g}</parameter>
            <parameter id="ucldStdev.c:{prefix}" spec="parameter.RealParameter" lower="0.0" name="stateNode">0.1</parameter>
            <stateNode id="rateCategories.c:{prefix}" spec="parameter.IntegerParameter" dimension="{2*n-2}">1</stateNode>
        </state>

        <init id="RandomTree.t:{prefix}" spec="RandomTree" estimate="false" initial="@Tree.t:{prefix}" taxa="@{prefix}">
            <populationModel id="ConstantPopulation0.t:{prefix}" spec="ConstantPopulation">
                <parameter id="randomPopSize.t:{prefix}" spec="parameter.RealParameter" name="popSize">1.0</parameter>
            </populationModel>
        </init>

        <distribution id="posterior" spec="CompoundDistribution">

            <distribution id="prior" spec="CompoundDistribution">
                <distribution id="CoalescentConstant.t:{prefix}" spec="Coalescent">
                    <populationModel id="ConstantPopulation.t:{prefix}" spec="ConstantPopulation" popSize="@popSize.t:{prefix}"/>
                    <treeIntervals id="TreeIntervals.t:{prefix}" spec="beast.base.evolution.tree.TreeIntervals" tree="@Tree.t:{prefix}"/>
                </distribution>
                <prior id="PopSizePrior.t:{prefix}" name="distribution" x="@popSize.t:{prefix}">
                    <OneOnX id="OneOnX.0" name="distr"/>
                </prior>
                <prior id="KappaPrior.s:{prefix}" name="distribution" x="@kappa.s:{prefix}">
                    <LogNormal id="LogNormalDistributionModel.0" name="distr" M="1.0" S="1.25"/>
                </prior>
                <prior id="GammaShapePrior.s:{prefix}" name="distribution" x="@gammaShape.s:{prefix}">
                    <Exponential id="Exponential.0" name="distr" mean="1.0"/>
                </prior>
                <!-- Rate prior centred on the TempEst root-to-tip estimate.
                     Wide enough (S=1.0) that the data can move it. -->
                <prior id="ucldMeanPrior.c:{prefix}" name="distribution" x="@ucldMean.c:{prefix}">
                    <LogNormal id="LogNormalDistributionModel.rate" name="distr" M="{rate:g}" S="1.0" meanInRealSpace="true"/>
                </prior>
                <prior id="ucldStdevPrior.c:{prefix}" name="distribution" x="@ucldStdev.c:{prefix}">
                    <Exponential id="Exponential.stdev" name="distr" mean="0.3337"/>
                </prior>
            </distribution>

            <distribution id="likelihood" spec="CompoundDistribution" useThreads="true">
                <distribution id="treeLikelihood.{prefix}" spec="TreeLikelihood" data="@{prefix}" tree="@Tree.t:{prefix}">
                    <siteModel id="SiteModel.s:{prefix}" spec="SiteModel" gammaCategoryCount="4" shape="@gammaShape.s:{prefix}">
                        <parameter id="mutationRate.s:{prefix}" spec="parameter.RealParameter" estimate="false" lower="0.0" name="mutationRate">1.0</parameter>
                        <parameter id="proportionInvariant.s:{prefix}" spec="parameter.RealParameter" estimate="false" lower="0.0" name="proportionInvariant" upper="1.0">0.0</parameter>
                        <substModel id="hky.s:{prefix}" spec="HKY" kappa="@kappa.s:{prefix}">
                            <frequencies id="estimatedFreqs.s:{prefix}" spec="Frequencies" frequencies="@freqParameter.s:{prefix}"/>
                        </substModel>
                    </siteModel>
                    <branchRateModel id="RelaxedClock.c:{prefix}" spec="beast.base.evolution.branchratemodel.UCRelaxedClockModel" clock.rate="@ucldMean.c:{prefix}" rateCategories="@rateCategories.c:{prefix}" tree="@Tree.t:{prefix}">
                        <LogNormal id="LogNormalDistributionModel.c:{prefix}" S="@ucldStdev.c:{prefix}" meanInRealSpace="true" name="distr" M="1.0"/>
                    </branchRateModel>
                </distribution>
            </distribution>
        </distribution>

        <!-- Classic operators: stable across BEAST 2.6/2.7. The Bactrian kernel
             variants mix slightly better but live in packages whose paths have
             moved between versions. -->
        <operator id="KappaScaler.s:{prefix}" spec="ScaleOperator" parameter="@kappa.s:{prefix}" scaleFactor="0.5" weight="0.1"/>
        <operator id="gammaShapeScaler.s:{prefix}" spec="ScaleOperator" parameter="@gammaShape.s:{prefix}" scaleFactor="0.5" weight="0.1"/>
        <operator id="FrequenciesExchanger.s:{prefix}" spec="DeltaExchangeOperator" delta="0.01" weight="0.1" parameter="@freqParameter.s:{prefix}"/>
        <operator id="PopSizeScaler.t:{prefix}" spec="ScaleOperator" parameter="@popSize.t:{prefix}" scaleFactor="0.75" weight="3.0"/>
        <operator id="ucldMeanScaler.c:{prefix}" spec="ScaleOperator" parameter="@ucldMean.c:{prefix}" scaleFactor="0.5" weight="1.0"/>
        <operator id="ucldStdevScaler.c:{prefix}" spec="ScaleOperator" parameter="@ucldStdev.c:{prefix}" scaleFactor="0.5" weight="3.0"/>
        <operator id="CategoriesRandomWalk.c:{prefix}" spec="IntRandomWalkOperator" parameter="@rateCategories.c:{prefix}" weight="10.0" windowSize="1"/>
        <operator id="CategoriesSwapOperator.c:{prefix}" spec="SwapOperator" intparameter="@rateCategories.c:{prefix}" weight="10.0"/>
        <operator id="CategoriesUniform.c:{prefix}" spec="UniformOperator" parameter="@rateCategories.c:{prefix}" weight="10.0"/>

        <operator id="CoalescentConstantTreeScaler.t:{prefix}" spec="ScaleOperator" scaleFactor="0.5" tree="@Tree.t:{prefix}" weight="3.0"/>
        <operator id="CoalescentConstantTreeRootScaler.t:{prefix}" spec="ScaleOperator" rootOnly="true" scaleFactor="0.5" tree="@Tree.t:{prefix}" weight="3.0"/>
        <operator id="CoalescentConstantUniformOperator.t:{prefix}" spec="Uniform" tree="@Tree.t:{prefix}" weight="30.0"/>
        <operator id="CoalescentConstantSubtreeSlide.t:{prefix}" spec="SubtreeSlide" tree="@Tree.t:{prefix}" weight="15.0"/>
        <operator id="CoalescentConstantNarrow.t:{prefix}" spec="Exchange" tree="@Tree.t:{prefix}" weight="15.0"/>
        <operator id="CoalescentConstantWide.t:{prefix}" spec="Exchange" isNarrow="false" tree="@Tree.t:{prefix}" weight="3.0"/>
        <operator id="CoalescentConstantWilsonBalding.t:{prefix}" spec="WilsonBalding" tree="@Tree.t:{prefix}" weight="3.0"/>

        <logger id="tracelog" spec="Logger" fileName="{prefix}.log" logEvery="{log_every}" model="@posterior" sanitiseHeaders="true" sort="smart">
            <log idref="posterior"/>
            <log idref="likelihood"/>
            <log idref="prior"/>
            <log idref="treeLikelihood.{prefix}"/>
            <log id="TreeHeight.t:{prefix}" spec="beast.base.evolution.tree.TreeStatLogger" tree="@Tree.t:{prefix}"/>
            <log idref="kappa.s:{prefix}"/>
            <log idref="gammaShape.s:{prefix}"/>
            <log idref="freqParameter.s:{prefix}"/>
            <log idref="popSize.t:{prefix}"/>
            <log idref="ucldMean.c:{prefix}"/>
            <log idref="ucldStdev.c:{prefix}"/>
            <log id="rate.c:{prefix}" spec="beast.base.evolution.RateStatistic" branchratemodel="@RelaxedClock.c:{prefix}" tree="@Tree.t:{prefix}"/>
            <log idref="CoalescentConstant.t:{prefix}"/>
        </logger>

        <logger id="screenlog" spec="Logger" logEvery="{log_every}">
            <log idref="posterior"/>
            <log idref="likelihood"/>
            <log idref="prior"/>
        </logger>

        <logger id="treelog.t:{prefix}" spec="Logger" fileName="{prefix}.trees" logEvery="{log_every}" mode="tree">
            <log id="TreeWithMetaDataLogger.t:{prefix}" spec="beast.base.evolution.TreeWithMetaDataLogger" branchratemodel="@RelaxedClock.c:{prefix}" tree="@Tree.t:{prefix}"/>
        </logger>

        <operatorschedule id="OperatorSchedule" spec="OperatorSchedule"/>
    </run>
</beast>
'''


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--aln", required=True, type=Path)
    ap.add_argument("--out", required=True, type=Path, help="Output directory")
    ap.add_argument("--prefix", default=None)
    ap.add_argument("--rate", type=float, default=7.46e-4,
                    help="Clock rate prior mean, subs/site/year (default %(default)g)")
    ap.add_argument("--chain", type=int, default=100_000_000)
    ap.add_argument("--log-every", type=int, default=None,
                    help="Default: chain/10000, giving ~10k samples")
    ap.add_argument("--randomize-dates", type=int, default=0,
                    help="Generate N date-randomised replicates for the DRT")
    ap.add_argument("--seed", type=int, default=20260819)
    args = ap.parse_args()

    if not args.aln.is_file():
        print(f"Alignment not found: {args.aln}", file=sys.stderr)
        return 1

    seqs = read_fasta(args.aln)
    info, bad = parse_labels(seqs)
    if bad:
        print(f"ERROR: {len(bad)} labels not in ACCESSION|host|year form, e.g. {bad[:3]}",
              file=sys.stderr)
        return 1
    seqs = {k: v for k, v in seqs.items() if k in info}

    lengths = {len(s) for s in seqs.values()}
    if len(lengths) != 1:
        print(f"ERROR: sequences differ in length {sorted(lengths)[:4]} — not aligned.",
              file=sys.stderr)
        return 1

    prefix = args.prefix or args.aln.stem.replace("-", "_")
    log_every = args.log_every or max(args.chain // 10000, 1000)
    args.out.mkdir(parents=True, exist_ok=True)

    years = [info[k][2] for k in seqs]
    hosts = {}
    for k in seqs:
        hosts[info[k][1]] = hosts.get(info[k][1], 0) + 1

    print(f"{len(seqs)} sequences, {lengths.pop()} sites")
    print(f"date range: {min(years):.2f} - {max(years):.2f} ({max(years)-min(years):.1f} yrs)")
    print(f"host groups: {dict(sorted(hosts.items(), key=lambda kv: -kv[1]))}")
    print(f"rate prior mean: {args.rate:g}   chain: {args.chain:,}   log every: {log_every:,}\n")

    thin = {h: n for h, n in hosts.items() if n < 5}
    if thin:
        print(f"WARNING: host groups with <5 sequences: {thin}")
        print("  Discrete trait analysis will be unreliable for these — consider merging.\n")

    # --- traits file for BEAUti ------------------------------------------
    traits_path = args.out / f"{prefix}_traits.txt"
    with traits_path.open("w") as fh:
        fh.write("traits\thost\n")
        for k in seqs:
            fh.write(f"{k}\t{info[k][1]}\n")
    print(f"wrote {traits_path}   <- import this in BEAUti for the discrete trait")

    # --- main XML ---------------------------------------------------------
    xml = build_xml(seqs, info, args.rate, args.chain, log_every, prefix)
    main_path = args.out / f"{prefix}.xml"
    main_path.write_text(xml)
    try:
        ET.fromstring(xml)
        print(f"wrote {main_path}   (well-formed XML)")
    except ET.ParseError as exc:
        print(f"wrote {main_path}   BUT XML IS MALFORMED: {exc}", file=sys.stderr)
        return 1

    # --- date randomised replicates ---------------------------------------
    if args.randomize_dates:
        rng = random.Random(args.seed)
        drt_dir = args.out / "date_randomised"
        drt_dir.mkdir(exist_ok=True)
        for i in range(1, args.randomize_dates + 1):
            shuffled = list(years)
            rng.shuffle(shuffled)
            info_r = {k: (info[k][0], info[k][1], shuffled[j])
                      for j, k in enumerate(seqs)}
            xml_r = build_xml(seqs, info_r, args.rate, args.chain, log_every,
                              f"{prefix}_drt{i}",
                              seed_note=f"DATE-RANDOMISED REPLICATE {i} — dates shuffled, "
                                        "for the temporal signal test. NOT a real analysis.")
            (drt_dir / f"{prefix}_drt{i}.xml").write_text(xml_r)
        print(f"wrote {args.randomize_dates} date-randomised replicates -> {drt_dir}")
        print("  Run these, then compare the ucldMean 95% HPDs against the real analysis.")
        print("  Real estimate outside the randomised distribution = genuine temporal signal.")

    print(f"""
NEXT STEPS

1. Open {main_path.name} in BEAUti (File > Load) and confirm it parses cleanly.
   This is your check that the XML matches your BEAST version. Do it before
   committing days of compute.

2. Add the discrete trait analysis in BEAUti:
     - Install BEAST_CLASSIC via File > Manage Packages (restart BEAUti after)
     - Tip Dates tab: confirm dates loaded, 'since some time in the past' unticked
     - Add a trait partition and import {traits_path.name}
     - Set the trait substitution model to asymmetric, tick BSSVS
     - BSSVS matters: it identifies which host transitions are actually supported
       rather than fitting every possible one
     - Save the XML

3. Test run: chainLength 1000000, confirm it starts and the likelihood climbs.

4. Full run, at least 2 independent chains with different seeds:
     beast -seed 12345 -threads 4 {prefix}.xml
     beast -seed 54321 -threads 4 {prefix}.xml

5. Tracer: every parameter ESS > 200, chains converged on the same values.

6. Date randomisation test, then TreeAnnotator for the MCC tree.
""")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
